main:
  # Токен бота
  token: TOKEN

  # Во что бот играет
  game_activity: GAME ACTIVITY

  # ID роли или пользователя которому хотите дать доступ к админским командам
  admins:
    - USER_ID

  # ID пользователя которому будут отправляться сообщения об ошибках
  owner: USER_ID

  # Отвечает за использование бота только в ЛС (Админская часть не учитывается, она только на сервере)
  private_message_only: true

  # Отвечает за использование дополнения EMarket (влияет на бд)
  use_market: true

db:
  host: HOST
  user: USER
  password: PASSWORD
  db: DB
  port: PORT

channels:
  # Создание карты
  create_card_channel: CHANNEL

  # Переводы
  transfer_channel: CHANNEL

  # Изменение карты по умолчанию
  set_default_channel: CHANNEL

  # Изменение баланса
  balance_channel: CHANNEL

  # Штрафы
  fine_channel: CHANNEL

  # Запуск бота
  start_channel: CHANNEL

  # Клановые карты
  clan_user_channel: CHANNEL

