main:
  # Токен бота
  token: MTE0ODAwNzQ1Nzk0NDI0MDE1OA.GoevFD.IW6ODYpMb87aIR0rzW3rdLDZ7n9NkIZuSB5Etc

  # Во что бот играет
  game_activity: ЭмблаX

db:
  host: 192.168.1.119
  user: enderbank
  password: 7UjM_buSjv
  db: EnderBank
  port: 3306

channels:
  # Создание карты
  create_card_channel: 1172226563593482300

  # Переводы
  transfer_channel: 1172226634829537280

  # Изменение карты по умолчанию
  set_default_channel: 1172226634829537280

  # Изменение баланса
  balance_channel: 1172226666236485643

  # Штрафы
  fine_channel: 1172226710368952423

  # Запуск бота
  start_channel: 1172226791621009488

  # Клановые карты
  clan_user_channel: 1172226769668034640

